spring:
  application:
    name: Cloudwise
  datasource:
    url: jdbc:h2:mem:ApplicationsLibrary;NON_KEYWORDS=USER
    driver-class-name: org.h2.Driver
    username: user
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
springdoc:
  swagger-ui:
    path: /docs